# Generated by Django 5.2.7 on 2025-11-16 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_message_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["status"],
                "permissions": [("can_view_statistics", "Can view statistics")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
